name: baseline-builder-py
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas
    - numpy
    - openpyxl
    - matplotlib
    - scipy
    - pyyaml
    - pytest
